#!/system/bin/sh

#Set governor CPU 0 to performance and set min-max freq to 1200 MHz 
echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
echo "1200000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;
echo "1200000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;

#Set governor CPU 1 to performance and set min-max freq to 1200 MHz 
echo "performance" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
echo "1200000" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq;
echo "1200000" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq;

#Set governor CPU 2 to performance and set min-max freq to 1200 MHz 
echo "performance" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
echo "1200000" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq;
echo "1200000" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq;

#Set governor CPU 3 to performance and set min-max freq to 1200 MHz 
echo "performance" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
echo "1200000" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq;
echo "1200000" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq;

#Checking root access
id=`id`; id=`$busybox echo ${id#*=}`; id=`$busybox echo ${id%%\(*}`; id=`$busybox echo ${id%% *}`

if [ "$id" != "0" ] && [ "$id" != "root" ]; then
	$busybox sleep 2
	$busybox echo ""
	$busybox echo ""
	$busybox echo "You haven't ROOT access..."
	$busybox echo "Please type su"
	$busybox echo ""
	$busybox sleep 1
	exit
else
  $busybox echo ""
  $busybox echo "Set CPU profile performance succeded!" 
  $busybox echo ""
fi
